name: Build Search Index

on:
  push:
    paths:
      - 'research-database.json'
      - 'scripts/build-search-index.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build search index
      run: npm run build
    
    - name: Commit search index
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add search-index.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update search index"
        git push